package com.henriquesebastiao.downtify.core.model

fun track(
    id: String,
    title: String = "Song $id",
    album: String = "Album",
    albumArtist: String = "Artist",
    albumId: String = "alb-${album.lowercase()}",
    artistId: String = "art-${albumArtist.lowercase()}",
    trackNumber: Int = 0,
    year: String = "2024",
    duration: Double = 200.0,
    added: Long = 0,
    hasCover: Boolean = true,
    codec: String = "flac",
    bitrate: Int = 900_000,
) = Track(
    id = id,
    file = "$albumArtist - $title.flac",
    title = title,
    artist = albumArtist,
    artists = listOf(albumArtist),
    album = album,
    albumArtist = albumArtist,
    albumId = albumId,
    artistId = artistId,
    trackNumber = trackNumber,
    year = year,
    duration = duration,
    codec = codec,
    bitrate = bitrate,
    sampleRate = 44_100,
    channels = 2,
    size = 1_000,
    added = added,
    hasCover = hasCover,
    playlists = emptyList(),
)
