package com.henriquesebastiao.downtify.core.designsystem.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// Tokens from the approved design (Tokens board). Roles the board doesn't name
// are filled in to match: same hue family, M3 tone steps.

/** Downtify's dark scheme — the default. */
val DowntifyDarkColors = darkColorScheme(
    primary = Color(0xFF1AD05C),
    onPrimary = Color(0xFF04140A),
    primaryContainer = Color(0xFF0F3F24),
    onPrimaryContainer = Color(0xFF9DF2B8),
    inversePrimary = Color(0xFF006D32),
    secondary = Color(0xFFB4CCBB),
    onSecondary = Color(0xFF1F352A),
    secondaryContainer = Color(0xFF243A2D),
    onSecondaryContainer = Color(0xFFCDEBD6),
    tertiary = Color(0xFFA3C9D6),
    onTertiary = Color(0xFF04323D),
    tertiaryContainer = Color(0xFF1E4A57),
    onTertiaryContainer = Color(0xFFC8E6F0),
    background = Color(0xFF0B0C0E),
    onBackground = Color(0xFFE6E8E7),
    surface = Color(0xFF0B0C0E),
    onSurface = Color(0xFFE6E8E7),
    surfaceVariant = Color(0xFF282A2E),
    onSurfaceVariant = Color(0xFFA7ACAA),
    surfaceTint = Color(0xFF1AD05C),
    inverseSurface = Color(0xFFE6E8E7),
    inverseOnSurface = Color(0xFF1E2023),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    outline = Color(0xFF6E7471),
    outlineVariant = Color(0xFF34373A),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFF2E3134),
    surfaceDim = Color(0xFF0B0C0E),
    surfaceContainerLowest = Color(0xFF08090A),
    surfaceContainerLow = Color(0xFF121416),
    surfaceContainer = Color(0xFF17191C),
    surfaceContainerHigh = Color(0xFF1E2023),
    surfaceContainerHighest = Color(0xFF282A2E),
)

val DowntifyLightColors = lightColorScheme(
    primary = Color(0xFF006D32),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFF7EF8A6),
    onPrimaryContainer = Color(0xFF00210C),
    inversePrimary = Color(0xFF1AD05C),
    secondary = Color(0xFF4E6354),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFCFE9D6),
    onSecondaryContainer = Color(0xFF0B2014),
    tertiary = Color(0xFF3A6472),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFBEE9FA),
    onTertiaryContainer = Color(0xFF001F28),
    background = Color(0xFFF8FAF8),
    onBackground = Color(0xFF141715),
    surface = Color(0xFFF8FAF8),
    onSurface = Color(0xFF141715),
    surfaceVariant = Color(0xFFE0E3E1),
    onSurfaceVariant = Color(0xFF4A504C),
    surfaceTint = Color(0xFF006D32),
    inverseSurface = Color(0xFF2D312E),
    inverseOnSurface = Color(0xFFEFF1EF),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    outline = Color(0xFF7A807C),
    outlineVariant = Color(0xFFC3C8C4),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFFF8FAF8),
    surfaceDim = Color(0xFFD8DBD9),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF2F4F2),
    surfaceContainer = Color(0xFFEDF0EE),
    surfaceContainerHigh = Color(0xFFE6E9E7),
    surfaceContainerHighest = Color(0xFFE0E3E1),
)
